name: lint

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  calledFromMainMatrix:
    if: inputs.environment == 'dev'
    name: Matrix Test
    runs-on: ubuntu-latest
    steps:
      - name: test matrix
        run: |
            echo "running the steps for ${{ inputs.environment }}"