name: lint

on:
  workflow_call:
    inputs:
      my_variable:
        required: true
        type: string

jobs:
  calledFromMainMatrix:
    name: Matrix Test
    runs-on: ubuntu-latest
    steps:
      - name: test matrix
        run: |
            echo "running the steps for ${{ inputs.my_variable }}"