name: lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint code
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./scripts/lint.ps1
        azPSVersion: "latest"