name: lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    #- name: Lint code
    #  run: |
    #    $templatesObject = Get-Content -Raw -Path './templates/templates.json' | ConvertFrom-Json
    #    foreach ($template in $templatesObject.templates) {
    #        Write-Host $template.name
    #        az bicep build --file "./templates/bicep/$($template.name).bicep"
    #    }

    - name: Lint code
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./scripts/lint.ps1
        azPSVersion: "latest"