name: Loop With Matrix

# Controls when the workflow will run
on:
  workflow_dispatch:

my_loop_job:
    name: loop job
    runs-on: my-github-runners
    strategy:
      matrix:
        my_variable: [ "var1", "var2", "var3" ]
        
   steps:
    - name: test loop
      run: |
          echo "running the steps for $my_variable"