name: Azure ARM

# Controls when the workflow will run
on: [push]

jobs:
  # Lint the Bicep file.
  #lint:
  #  uses: aaproto/githubactions-common/.github/workflows/lint.yml@main

  lint-build-and-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}