name: Azure ARM

# Controls when the workflow will run
on:
  #push:
  workflow_dispatch:

jobs:
  # Lint the Bicep file.
  #lint:
  #  uses: aaproto/githubactions-common/.github/workflows/lint.yml@main

  lint-build-and-deploy:
    uses: aaproto/githubactions-common/.github/workflows/deploy.yml@main
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}