name: Main Matrix

on:
  workflow_dispatch:

jobs:
  # Lint the Bicep file.
  testmatrix:
    strategy:
      matrix:
        environment: ['dev', 'tst', 'prd']
    uses: ./.github/workflows/callFromMainMatrix.yml
    with:
      environment: ${{ matrix.environment }}