name: Azure ARM

# Controls when the workflow will run
on: [push]

jobs:
  # Lint the Bicep file.
  lint:
    uses: aaproto/githubactions-common/.github/workflows/workflow-1.yml

  build-and-deploy:
    needs: lint
    uses: ./.github/workflows/deploy.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}