name: Main Matrix

on:
  workflow_dispatch:

jobs:
  # Lint the Bicep file.
  testmatrix:
    strategy:
      matrix:
        variable: ['var1', 'var2', 'var3']
    uses: ./.github/workflows/callFromMainMatrix.yml
    with:
      my_variable: ${{ matrix.variable }}